### ISSUE TITLE
The abstract methods are missing the command_logger input

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/cloudshell-L1-networking-core#11]
The request_handler is sending the driver_handler the command_logger input.
This is missing in the abstract method definition of the map_bidi/map_uni/etc commands.
So you get some warnings about it.

https://github.com/QualiSystems/cloudshell-L1-networking-core/blob/dev/common/driver_handler_base.py#L19

https://github.com/QualiSystems/cloudshell-L1-networking-core/blob/dev/common/request_handler.py#L67

**Comment by Costya-Y** [comment]
Hi Yaniv,

We changed the code and there is no request_handler anymore. In the same time right now loggers will be created once in L1 Driver main.py

Thank you,
Costya
