### ISSUE TITLE
common.cli tcp_session.connect and expect_session.hardware_expect

### ISSUE THREAD

**Issue by kswamidoss** [QualiSystems/cloudshell-L1-networking-core#8]
Currently the common.cli.tcp_session.connect method has an expect_session.hardware_expect call which requires an re_string argument. For TCP sessions with devices that have no prompt, the tcp_session.connect call therefore times out. Would be nice in tcp_session.connect to make the hardware_expect call optional.

tcp_session.connect:
output = self.hardware_expect(re_string=re_string)

expect_session.hardware_expect:
        if re_string is None or len(re_string) == 0:
            raise Exception('ExpectSession', 'List of expected messages can\'t be empty!')

**Comment by GalcQuali** [comment]
We are in the process of updating our L1 template to use the cloudshell-cli package which already contain the above.

**Comment by yaroslavNqualisystems** [comment]
We have removed cli from the package.
Use cloudshell-cli package.
